export const FETCH_PLANETS = 'FETCH_PLANETS';
export const CONNECTION_ERROR = 'CONNECTION_ERROR';
export const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS';
export const DATA_REQUEST = 'DATA_REQUEST';
export const DATA_RECIEVED = 'DATA_RECIEVED';